#include "renewal/generator.hpp"

#include <algorithm>
#include <expected>
#include <filesystem>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "renewal/manifest_parser.hpp"
#include "renewal/utils.hpp"
#include "renewal/validator.hpp"

namespace renewal {

namespace fs = std::filesystem;

namespace {

struct PackageBundle {
  fs::path root;
  PackageManifest manifest;
};

std::vector<fs::path> collect_manifests(const fs::path& root_path) {
  std::vector<fs::path> manifests;
  const fs::path manifest_path = root_path / "pkg.toml";
  if (fs::exists(manifest_path)) {
    manifests.push_back(manifest_path);
  }

  if (!fs::exists(root_path) || !fs::is_directory(root_path)) {
    return manifests;
  }

  for (const auto& entry : fs::recursive_directory_iterator(root_path)) {
    if (!entry.is_regular_file() || entry.path().filename() != "pkg.toml") {
      continue;
    }
    if (entry.path() == manifest_path) {
      continue;
    }
    manifests.push_back(entry.path());
  }

  std::sort(manifests.begin(), manifests.end());
  manifests.erase(std::unique(manifests.begin(), manifests.end()),
                  manifests.end());
  return manifests;
}

std::vector<fs::path> collect_module_interfaces(
    const fs::path& package_root, const std::string& package_name) {
  std::vector<fs::path> files;
  const fs::path module_root = package_root / "modules" / package_name;
  if (!fs::exists(module_root)) {
    return files;
  }

  for (const auto& entry : fs::recursive_directory_iterator(module_root)) {
    if (entry.is_regular_file() && entry.path().extension() == ".cppm") {
      files.push_back(entry.path());
    }
  }

  std::sort(files.begin(), files.end());
  return files;
}

std::string quote_path(const fs::path& path) {
  return "\"" + path.generic_string() + "\"";
}

}  // namespace

std::expected<std::string, std::string> generate_cmake(
    const fs::path& root_path) {
  auto validation = validator(root_path);
  if (!validation) {
    return std::unexpected(validation.error());
  }

  const auto manifests = collect_manifests(root_path);
  if (manifests.empty()) {
    return std::unexpected("No pkg.toml found under: " + root_path.string());
  }

  std::vector<PackageBundle> packages;
  packages.reserve(manifests.size());
  for (const auto& manifest_path : manifests) {
    auto parse_result = parse_manifest(manifest_path);
    if (!parse_result.ok()) {
      return std::unexpected("Manifest became invalid during generation: " +
                             manifest_path.string());
    }
    packages.push_back({manifest_path.parent_path(), parse_result.manifest});
  }

  std::sort(packages.begin(), packages.end(),
            [](const PackageBundle& lhs, const PackageBundle& rhs) {
              return lhs.manifest.package.name.value_or("") <
                     rhs.manifest.package.name.value_or("");
            });

  std::ostringstream output;
  output << "# Generated by Renewal\n";
  output << "# Root: " << fs::absolute(root_path).generic_string() << "\n\n";

  for (const auto& package : packages) {
    const std::string& package_name = *package.manifest.package.name;
    const std::string& target_name = *package.manifest.build.target;

    const auto module_interfaces =
        collect_module_interfaces(package.root, package_name);
    if (module_interfaces.empty()) {
      return std::unexpected("No module interface units found for package '" +
                             package_name + "'");
    }

    output << "add_library(" << target_name << ")\n\n";
    output << "target_sources(" << target_name << "\n";
    output << "  PUBLIC\n";
    output << "    FILE_SET cxxmods TYPE CXX_MODULES\n";
    output << "    FILES\n";
    for (const auto& file : module_interfaces) {
      output << "      "
             << quote_path(fs::relative(file, fs::absolute(root_path))) << "\n";
    }

    if (!package.manifest.build.sources.empty()) {
      output << "  PRIVATE\n";
      for (const auto& source : package.manifest.build.sources) {
        output << "      "
               << quote_path(fs::relative(package.root / source,
                                          fs::absolute(root_path)))
               << "\n";
      }
    }
    output << ")\n";

    std::set<std::string> local_deps;
    for (const auto& [dep_name, dep_spec] : package.manifest.deps) {
      if (dep_spec.kind != DependencyKind::Path) {
        continue;
      }

      const fs::path dep_manifest = package.root / dep_spec.value / "pkg.toml";
      auto parse_result = parse_manifest(dep_manifest);
      if (!parse_result.ok() || !parse_result.manifest.build.target) {
        continue;
      }
      local_deps.insert(*parse_result.manifest.build.target);
    }

    if (!local_deps.empty()) {
      output << "target_link_libraries(" << target_name << "\n";
      output << "  PUBLIC\n";
      for (const auto& dep_target : local_deps) {
        output << "    " << dep_target << "\n";
      }
      output << ")\n";
    }

    output << "\n";
  }

  return output.str();
}

}  // namespace renewal
